#!/bin/sh /etc/rc.common

# Start/stop script for wayru-os-services
START=99
STOP=99

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/wayru-os-services
	procd_set_param respawn 150 10 10
	procd_set_param term_timeout 60
	procd_set_param stdout 1
	procd_close_instance
}

stop_service() {
	logger -s "wayru-os-services stopping"
}
