#!/bin/sh /etc/rc.common

START=95
STOP=95

USE_PROCD=1

start_service() {

    logger -t fry-config "Starting fry-config service"

    procd_open_instance
    procd_set_param command /usr/bin/fry-config
    procd_set_param file /etc/config/fry-config
    procd_set_param respawn 3600 60 0
    procd_set_param term_timeout 30
    procd_set_param stdout 1
    procd_close_instance
}

stop_service() {
	logger -s "fry-config stopping"
}

reload_service() {
	stop
	start
}
