#!/bin/sh /etc/rc.common

START=95
STOP=95

USE_PROCD=1

start_service() {
    
    logger -t wayru-config "Starting wayru-config service"
    
    procd_open_instance
    procd_set_param command /usr/bin/wayru-config
    procd_set_param file /etc/config/wayru-config
    procd_set_param respawn 3600 60 0
    procd_set_param term_timeout 30
    procd_set_param stdout 1
    procd_close_instance
}

stop_service() {
	logger -s "wayru-config stopping"
}

reload_service() {
	stop
	start
}